name: Update Streaming News (disabled)

on:
  workflow_dispatch: {}

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Disabled
        run: echo "News generator workflow has been disabled."
